### ISSUE TITLE
NO directory found

### ISSUE THREAD

**Issue by sukannyapurkayastha** [Dru-Mara/EvalNE#1]
IOError: [Errno 2] No such file or directory: './emb.tmp' while running python evalne ./examples/conf_parTest.ini

**Comment by Dru-Mara** [comment]
Hi,

Can you post the whole stack trace error? With that, I could tell you for sure, however, generally this kind of error means that one of the methods you were trying to evaluate was not found (it's not installed or the path was wrong). The methods evaluated are expected to generate as output a file called "emb.tmp" from which the library will read the embeddings. Make sure all the methods you are trying to evaluate are installed and the paths are correct.

Alex

**Comment by sukannyapurkayastha** [comment]
I/O error(2): No such file or directory while evaluating method node2vec
Traceback (most recent call last):
  File "simple-example.py", line 42, in <module>
    edge_embedding_methods=edge_emb, input_delim=' ', output_delim=' ')
  File "/home/user/anaconda3/envs/research_env/lib/python2.7/site-packages/evalne/evaluation/evaluator.py", line 679, in evaluate_cmd
    input_delim, output_delim, write_weights, write_dir, verbose)
  File "/home/user/anaconda3/envs/research_env/lib/python2.7/site-packages/evalne/evaluation/evaluator.py", line 725, in _evaluate_ne_cmd
    num_vectors = sum(1 for _ in open(tmpemb))

**Comment by Dru-Mara** [comment]
Precisely the 2-3 lines before the Traceback should tell you what the error was. For example, in the case below (where I reproduced your error) the system says that it's trying to evaluate a certain method and execute a Python call with some parameter. Then it tells you that Python can't open the file /wow/home/... because the path is incorrect. Check those lines above and see what they say (or post them here). You should find out if it's an incorrect path or the method to be evaluated just does not exist. 

Running command...
python /wow/home/alexandru/Downloads/GEM-master/main.py --input ./edgelist.tmp --output ./emb.tmp --dimension 128 --method hope --max_iter 100 --beta 0.1 1>/dev/null
python: can't open file '/wow/home/alexandru/Downloads/GEM-master/main.py': [Errno 2] No such file or directory
I/O error(2): No such file or directory while evaluating method hope-gem
Traceback (most recent call last):
  File "/home/alexandru/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/alexandru/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/alexandru/Desktop/EvalNE_master/evaluatinggraphembeddings/code/EvalNE/evalne/__main__.py", line 320, in <module>
    main()
  File "/home/alexandru/Desktop/EvalNE_master/evaluatinggraphembeddings/code/EvalNE/evalne/__main__.py", line 34, in main
    evaluate(setup)
  File "/home/alexandru/Desktop/EvalNE_master/evaluatinggraphembeddings/code/EvalNE/evalne/__main__.py", line 106, in evaluate
    times.extend(eval_other(setup, nee))
  File "/home/alexandru/Desktop/EvalNE_master/evaluatinggraphembeddings/code/EvalNE/evalne/__main__.py", line 199, in eval_other
    verbose=setup.verbose)
  File "/home/alexandru/Desktop/EvalNE_master/evaluatinggraphembeddings/code/EvalNE/evalne/evaluation/evaluator.py", line 606, in evaluate_cmd
    input_delim, output_delim, write_weights, write_dir, verbose)
  File "/home/alexandru/Desktop/EvalNE_master/evaluatinggraphembeddings/code/EvalNE/evalne/evaluation/evaluator.py", line 744, in _evaluate_ne_cmd
    num_vectors = sum(1 for _ in open(tmpemb))
IOError: [Errno 2] No such file or directory: './emb.tmp'
